#!/bin/sh
# Find and replace PATTERN with REPLACEMENT in FILEs.

usage() {
    echo usage: far PATTERN REPLACEMENT FILE ...
    exit 1
}

ext='~'
case $# in
    [0-2])
        usage
        ;;
esac
a="$1"
b="$2"
shift 2
for ifile in `grep -rl "$a" $@`; do
    ofile="$ifile$ext"
    if [ -e "$ofile" ]; then
        echo $ofile already exists
        exit 1
    fi
    sed "s/$a/$b/g" "$ifile" >"$ofile"
    cat "$ofile" >"$ifile"
    rm -f "$ofile"
done
