#!/bin/sh
# Usage: far A B [FILE] ...
# Find and replace A with B in FILEs.
case $# in
    0)
        exit 1
        ;;
    1)
        exit 1
        ;;
    2)
        exit 1
        ;;
    3)
        exit 1
        ;;
esac
a="$1"
b="$2"
shift
shift
grep -rl "$a" $@ | xargs sed -i '' "s/$a/$b/g"
