#!/bin/sh

args=`getopt s:e $*`
set -- $args

eflag=0
sflag=0
ext=
for i do
    case "$i" in
        -e)
            eflag=1
            shift;;
        -s)
            sflag=1
            shift
            ext="$1"
            shift;;
        --)
            shift; break;;
    esac
done

shebang() {
    case $1 in
        py)
            echo '#!/usr/bin/env python'
            ;;
        *)
            echo '#!/bin/sh'
    esac
}

case $# in
    1)
        name="$1"
        if [[ -e "$name" ]]; then
            echo "$name" already exists >&2
            exit -1
        fi
        if [[ $ext == "" ]]; then
            ext=${name##*.}
        fi
        shebang "$ext" >"$name"
        chmod +x "$name"
        if [ $eflag -eq 1 ]; then
            "$EDITOR" "$name"
        fi
        ;;
    *)
        echo "usage: `basename $0` [-e] [-s suffix] filename" >&2
        exit 2
esac
