#!/bin/sh

usage() {
    echo usage: `basename $0` [-e] [-s suffix] filename >&2
    exit 2
}

eflag=false
ext=
while getopts es: opt; do
    case "$opt" in
        e)
            eflag=true
            ;;
        s)
            ext="$OPTARG"
            ;;
        ?)
            usage
            ;;
    esac
done

shebang() {
    case "$1" in
        py)
            echo '#!/usr/bin/env python'
            ;;
        *)
            echo '#!/bin/sh'
            ;;
    esac
}

shift $(($OPTIND - 1))
case "$#" in
    1)
        name="$1"
        if [ -e "$name" ]; then
            echo "$name" already exists >&2
            exit -1
        fi
        if [ -z $ext ]; then
            ext=${name##*.}
        fi
        shebang "$ext" >"$name"
        chmod +x "$name"
        if $eflag; then
            "$EDITOR" "$name"
        fi
        ;;
    *)
        usage
        ;;
esac
