#!/bin/sh

usage() {
    echo usage: `basename $0` [-e] [-s suffix] filename >&2
    exit 2
}

eflag=false
ext=
while getopts es: opt; do
    case "$opt" in
        e)
            eflag=true
            ;;
        s)
            ext="$OPTARG"
            ;;
        ?)
            usage
            ;;
    esac
done

shebang() {
    case "$1" in
        py)
            echo '#!/usr/bin/env python'
            echo '#-*-coding:utf-8-*-'
            echo 'from __future__ import absolute_import'
            echo 'from __future__ import division'
            echo 'from __future__ import print_function'
            echo 'from __future__ import unicode_literals'
            ;;
        py3)
            echo '#!/usr/bin/env python3'
            ;;
        *)
            echo '#!/bin/sh'
            ;;
    esac
}

shift $(($OPTIND - 1))
case "$#" in
    1)
        name="$1"
        if [ -e "$name" ]; then
            echo "$name" already exists >&2
            exit 1
        fi
        if [ -z $ext ]; then
            ext=${name##*.}
        fi
        shebang "$ext" >"$name"
        chmod +x "$name"
        if $eflag; then
            "$EDITOR" "$name"
        fi
        ;;
    *)
        usage
        ;;
esac
