#!/bin/sh

usage() {
    echo usage: `basename $0` [-c bytes] [-o file] >&2
    exit 1
}

bytes=20
ofile=/dev/stdout
while getopts c:o: opt; do
    case "$opt" in
        c)
            bytes="$OPTARG"
            ;;
        o)
            ofile="$OPTARG"
            ;;
        ?)
            usage
            ;;
    esac
done
shift $(($OPTIND - 1))
if [ "$#" -ne 0 ]; then
    usage
fi
head -c "$bytes" /dev/urandom >"$ofile"
