#!/usr/bin/env python
#-*-coding:utf-8-*-
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from __future__ import unicode_literals

import os
import shutil
import subprocess
import sys
import tempfile

progname = os.path.basename(sys.argv[0])
if len(sys.argv) < 2:
    print('usage: %s SRC [ARG] ...' % progname)
    exit(1)
tmp = tempfile.mkdtemp(prefix=progname)
src = sys.argv[1]
out = os.path.basename(src)
out, _ = os.path.splitext(out)
out = os.path.join(tmp, out)
args = sys.argv[2:]
if not subprocess.call(['cc', '-o', out, src]):
    subprocess.call([out] + args)
shutil.rmtree(tmp)
