#!/usr/bin/env python

import sys, turtle

def move_and_turn(fd, rt):
    turtle.forward(fd)
    turtle.right(rt)

def shitbrix(angle):
    for i in xrange(4):
        move_and_turn(30, angle)
        move_and_turn(10, angle)
        move_and_turn(20, -angle)
        move_and_turn(10, -angle)
        move_and_turn(20, angle)

for angle in sys.argv[1:]:
    shitbrix(int(angle))
    raw_input()
    turtle.clear()
